spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_lzy
    username: root
    password: 20000830
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3
  thymeleaf:
    cache: false

server:
  servlet:
    context-path: /masaki
